export const routes = {
  home: '/',
  login: '/login',
  order: '/order',
  orderEdit: '/order/edit',
  orderID: '/order/:id',
  orders: '/orders',
  ordersAdd: '/orders/add',
  ordersWithClient: '/orders/add/:id',
  invoice: '/invoices',
  products: '/products',
  productsAdd: '/products/add',
  productsEdit: '/products/edit',
  productsID: '/products/edit/:id',
  ProductDetail: '/products/:id',
  clients: '/clients',
  clientsAdd: '/clients/add',
  clientEdit: '/clients/edit',
  clientID: '/clients/edit/:id',
  employees: '/employees',
  employeesAdd: '/employees/add',
  employeesEdit: '/employees/edit',
  employeesID: '/employees/edit/:id',
  invoices: '/invoiceList',
  reservation: '/reservations',
  reservationAdd: 'reservation/add',
};
